using System;
using UnityEngine;

public enum AppLanguage
{
    Turkish = 0,
    English = 1
}

/// <summary>
/// Dil tercihi — PlayerPrefs ile kalıcı. KVKK: yalnızca dil kodu saklanır.
/// </summary>
public static class LanguageSettings
{
    private const string PrefKey = "app_language";
    private static bool _prefsDirty;

    public static event Action LanguageChanged;

    public static AppLanguage Current { get; private set; } = AppLanguage.Turkish;

    public static bool IsEnglish => Current == AppLanguage.English;

    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
    private static void Bootstrap()
    {
        int v = PlayerPrefs.GetInt(PrefKey, (int)AppLanguage.Turkish);
        Current = v == (int)AppLanguage.English ? AppLanguage.English : AppLanguage.Turkish;
    }

    public static void Set(AppLanguage lang)
    {
        if (Current == lang) return;
        Current = lang;
        PlayerPrefs.SetInt(PrefKey, (int)lang);
        _prefsDirty = true;
        LanguageChanged?.Invoke();
    }

    public static void Toggle()
    {
        Set(IsEnglish ? AppLanguage.Turkish : AppLanguage.English);
    }

    /// <summary>PlayerPrefs.Save senkron disk — dil tuşunda çağırma; debounce / çıkışta flush.</summary>
    public static void FlushPrefs()
    {
        if (!_prefsDirty) return;
        PlayerPrefs.Save();
        _prefsDirty = false;
    }
}

/// <summary>
/// UI / rapor / koç metinleri. Kod anahtarları İngilizce; değerler TR/EN.
/// </summary>
public static class Loc
{
    public static string T(string key)
    {
        return T(key, LanguageSettings.Current);
    }

    public static string T(string key, AppLanguage lang)
    {
        if (lang == AppLanguage.English)
            return En(key);
        return Tr(key);
    }

    public static string Format(string key, params object[] args)
    {
        return Format(key, LanguageSettings.Current, args);
    }

    public static string Format(string key, AppLanguage lang, params object[] args)
    {
        string fmt = T(key, lang);
        try { return string.Format(fmt, args); }
        catch { return fmt; }
    }

    private static string Tr(string key)
    {
        switch (key)
        {
            // Menu
            case "menu.subtitle": return "Yerel veriler · KVKK: menüden silebilirsiniz";
            case "menu.session.idle": return "Seans bekleniyor";
            case "menu.session.active": return "SEANS AKTİF";
            case "menu.session.done": return "Son seans tamamlandı";
            case "menu.card.rom": return "Son Maks ROM";
            case "menu.card.completion": return "Gelişim %";
            case "menu.card.compensation": return "Son Kompansasyon";
            case "menu.graph.title": return "Seanslar arası ROM gelişimi";
            case "menu.graph.legend": return "Mint: Sağ maks · Mavi: Sol maks · Mor: Zorlanma";
            case "menu.history.title": return "Seans geçmişi — Detay’a dokun";
            case "menu.history.loading": return "Yükleniyor…";
            case "menu.history.empty": return "Henüz kayıtlı seans yok.\nEgzersize başlayarak ilk seansı oluşturun.";
            case "menu.btn.start": return "Egzersize Başla";
            case "menu.btn.html": return "İlerleme Raporunu Aç";
            case "menu.btn.compare": return "Seansları Karşılaştır";
            case "menu.btn.folder": return "Rapor Klasörü";
            case "menu.btn.refresh": return "Yenile";
            case "menu.btn.delete": return "Verilerimi Sil";
            case "menu.btn.lang": return "English";
            case "menu.hist.session": return "Seans";
            case "menu.hist.sessionN": return "Seans {0}";
            case "menu.hist.rightRom": return "Sağ:";
            case "menu.hist.leftRom": return "Sol:";
            case "menu.hist.reps": return "tekrar";
            case "menu.hist.invalid": return "geçersiz";
            case "menu.hist.compensation": return "Kompansasyon";
            case "menu.hist.strainPeak": return "Zorlanma pik";
            case "side.right": return "Sağ";
            case "side.left": return "Sol";
            case "side.right.abbr": return "Sağ";
            case "side.left.abbr": return "Sol";
            case "menu.hist.dtw.right": return "DTW sağ";
            case "menu.hist.dtw.left": return "DTW sol";
            case "menu.card.progress": return "Gelişim %";
            case "menu.toggle.right": return "Sağ maks";
            case "menu.toggle.left": return "Sol maks";
            case "menu.toggle.avg": return "Ort";
            case "menu.toggle.strain": return "Zorlanma";
            case "filter.all": return "Tümü";
            case "filter.week": return "Son 7 gün";
            case "filter.month": return "Son 30 gün";
            case "filter.quarter": return "Son 90 gün";
            case "filter.last5": return "Son 5 seans";
            case "filter.last10": return "Son 10 seans";
            case "filter.last20": return "Son 20 seans";
            case "filter.withComp": return "Kompansasyonlu";
            case "filter.noComp": return "Kompansasyonsuz";
            case "filter.highStrain": return "Yüksek zorlanma (≥%55)";
            case "filter.incomplete": return "Hedef tamamlanmamış";
            case "filter.rightArm": return "Sağ kol ölçülmüş";
            case "filter.leftArm": return "Sol kol ölçülmüş";
            case "filter.exercise": return "Hareket";
            case "filter.region.shoulder": return "Omuz";
            case "filter.region.arm": return "Kol";
            case "filter.region.elbow": return "Dirsek";
            case "filter.region.neck": return "Boyun";
            case "filter.region.leg": return "Bacak";
            case "filter.region.ankle": return "Ayak bileği";
            case "filter.move.shoulderFlexion": return "Omuz fleksiyonu";
            case "filter.move.shoulderAbduction": return "Omuz abdüksiyonu";
            case "filter.label": return "Kalite";
            case "filter.date": return "Dönem";
            case "filter.quality": return "Kalite";
            case "progress.need2": return "≥2 seans";
            case "progress.split": return "Sağ:{0}  Sol:{1}";
            case "progress.rightOnly": return "Sağ {0}";
            case "progress.leftOnly": return "Sol {0}";
            case "progress.combined": return "{0}";
            case "hud.graph.right": return "Sağ";
            case "hud.graph.left": return "Sol";
            case "hud.graph.strain": return "Zorlanma";
            case "report.col.rightMax": return "Sağ Maks";
            case "report.col.leftMax": return "Sol Maks";
            case "report.col.rightReps": return "Sağ Tekrar";
            case "report.col.leftReps": return "Sol Tekrar";
            case "report.col.invalidRL": return "Geçersiz Sağ/Sol";
            case "report.progress.r": return "Gelişim Sağ";
            case "report.progress.l": return "Gelişim Sol";
            case "report.ui.maxSplit": return "Sağ maks: {0}°   Sol maks: {1}°";
            case "report.ui.avgSplit": return "Sağ ort: {0}°   Sol ort: {1}°";
            case "report.ui.duration": return "Süre: {0}:{1}";
            case "report.ui.repsSplit": return "Sağ: {0}/{1} (geçersiz {2})   Sol: {3}/{4} (geçersiz {5})";
            case "report.ui.repsOnly": return "Sağ: {0}   Sol: {1}";
            case "report.ui.dtwPrefix": return "Hareket uyumu (DTW): ";
            case "report.ui.dtwSuffix": return " — hedef hareket şablonuna göre.";
            case "report.filter": return "Filtre:";
            case "report.sessions.count": return "Seans";

            case "menu.hist.tapHint": return "Detay için satıra veya Detay’a dokun";
            case "menu.hist.detail": return "Detay";
            case "detail.title": return "Seans Detayı";
            case "detail.metrics": return "Sağ maks {0}° · Sol maks {1}° · Hedef {2}°\nTekrar {3}/{4} · Kompansasyon {5} · Pik zorlanma %{6}\nDTW sağ %{7} · DTW sol %{8}";
            case "detail.box.rom": return "<b>Hareket aralığı (ROM)</b>\nSağ omuz en yüksek: {0}°\nSol omuz en yüksek: {1}°\nSeans hedef açısı: {2}°";
            case "detail.box.session": return "<b>Seans özeti</b>\nTamamlanan tekrar: {0} / {1}\nKompansasyon uyarısı: {2}\nEn yüksek zorlanma: %{3}";
            case "detail.box.quality": return "<b>Hareket kalitesi (DTW)</b>\nSağ kol benzerlik: %{0}\nSol kol benzerlik: %{1}\n(100 = hedef şablona yakın)";
            case "detail.note.dtwBoth": return "• Hareket kalitesi (DTW): sağ %{0}, sol %{1}.";
            case "detail.note.dtwRight": return "• Hareket kalitesi (DTW) sağ: %{0}.";
            case "detail.note.dtwLeft": return "• Hareket kalitesi (DTW) sol: %{0}.";
            case "menu.hist.dtw": return "DTW";
            case "detail.chart.legend": return "Mint = sağ · Mavi = sol · Turuncu = hedef · Mor = zorlanma · Kırmızı = yardımlı · X = zaman (sn)";
            case "detail.chart.noSeries": return "Bu kayıtta zaman serisi yok (eski seans). Tam grafik için HTML raporunu açın.";
            case "detail.summary.title": return "AI rapor özeti";
            case "detail.summary.header": return "Klinik karar-destek özeti (kural tabanlı):";
            case "detail.summary.empty": return "Bu seans için özet üretilemedi.";
            case "detail.summary.disclaimer": return "Bu özet teşhis değildir; fizyoterapist değerlendirmesine yardımcı yerel bir özetdir.";
            case "detail.note.rightOnly": return "• Ölçüm sağ kol odaklı.";
            case "detail.note.leftOnly": return "• Ölçüm sol kol odaklı.";
            case "detail.note.bothArms": return "• Sağ ve sol kol ölçümü mevcut.";
            case "detail.note.noReps": return "• Geçerli tekrar kaydı yok veya tamamlanmamış.";
            case "detail.note.targetRepsMet": return "• Hedef tekrar sayısına ulaşıldı.";
            case "detail.note.targetRepsPct": return "• Hedef tekrarın yaklaşık %{0}'i tamamlandı.";
            case "detail.note.romMet": return "• Maksimum ROM hedef açıya ulaştı veya aştı.";
            case "detail.note.romBelow": return "• Maksimum ROM hedefin yaklaşık {0}° altında kaldı.";
            case "detail.note.noComp": return "• Gövdeni dik tuttun; kolunu kaldırmak için yana eğilmedin.";
            case "detail.note.mildComp": return "• Birkaç kez ({0}) gövdeni yana eğerek kolunu kaldırmaya çalıştın. Mümkünse gövdeni sabit tut.";
            case "detail.note.highComp": return "• Sıkça ({0} kez) gövdeni yana eğerek kolunu kaldırmaya çalıştın. Sonraki seanslarda gövdeni dik tutmaya odaklan.";
            case "detail.note.invalid": return "• Geçersiz tekrar: {0}.";
            case "detail.note.highStrain": return "• Yüksek zorlanma (pik %{0}) — sağ {1}° / sol {2}° civarında.";
            case "detail.note.strainOk": return "• Zorlanma makul aralıkta (pik %{0}, ort %{1}).";
            case "detail.note.quality": return "• Seans kalitesi ({0}): ort %{1}.";
            case "detail.note.romUp": return "• Önceki seansa göre maks ROM yaklaşık +{0}°.";
            case "detail.note.romDown": return "• Önceki seansa göre maks ROM yaklaşık −{0}°.";
            case "detail.note.romFlat": return "• Önceki seansa göre ROM benzer seviyede.";
            case "detail.note.strainUp": return "• Zorlanma önceki seansa göre yaklaşık +%{0} arttı.";
            case "detail.note.strainDown": return "• Zorlanma önceki seansa göre yaklaşık −%{0} azaldı.";
            case "detail.btn.back": return "Geri";
            case "detail.btn.html": return "Seans Raporunu Aç";
            case "detail.btn.survey": return "Klinisyen: anket";
            case "detail.btn.compare": return "Başka seansla karşılaştır";
            case "detail.btn.openPrev": return "Önceki seansı aç";
            case "detail.compare.title": return "Bu seans ↔ Önceki seans";
            case "detail.compare.none": return "Karşılaştırılacak önceki seans yok.";
            case "detail.compare.current": return "Bu seans";
            case "detail.compare.previous": return "Önceki seans";
            case "detail.compare.rom": return "Maks ROM\nSağ {0}° · Sol {1}°";
            case "detail.compare.reps": return "Tekrar\n{0} / {1}";
            case "detail.compare.comp": return "Gövde eğilme uyarısı\n{0} kez";
            case "detail.compare.strain": return "Zorlanma\n%{0}";
            case "detail.compare.dtw": return "Hareket kalitesi\nSağ %{0} · Sol %{1}";
            case "detail.compare.deltaRom": return "ROM farkı: {0}";
            case "detail.compare.deltaComp": return "Eğilme uyarısı farkı: {0}";
            case "detail.compare.close": return "Karşılaştırmayı kapat";
            case "compare.picker.title": return "Seans karşılaştır";
            case "compare.picker.hint": return "İki seans seçin. Rapor anında HTML olarak oluşturulur (her seans sonrası değil).";
            case "compare.picker.slotAEmpty": return "A: henüz seçilmedi — listeden dokunun";
            case "compare.picker.slotBEmpty": return "B: henüz seçilmedi — listeden dokunun";
            case "compare.picker.slotA": return "A: {0}";
            case "compare.picker.slotB": return "B: {0}";
            case "compare.picker.rowSub": return "Sağ {0}° · Sol {1}° · Eğilme {2}";
            case "compare.picker.empty": return "Karşılaştırılacak seans yok.";
            case "compare.picker.generate": return "HTML raporu oluştur";
            case "compare.picker.ready": return "Hazır — PIN sonrası rapor açılır.";
            case "compare.picker.needTwo": return "Devam için iki farklı seans seçin.";
            case "compare.picker.needData": return "Veri yöneticisi bulunamadı.";
            case "compare.report.title": return "Seans karşılaştırma raporu";
            case "compare.legend.better": return "İyileşme";
            case "compare.legend.worse": return "Kötüleşme / dikkat";
            case "compare.legend.same": return "Benzer";
            case "compare.section.metrics": return "Tüm ölçümler";
            case "compare.section.bars": return "Karşılaştırma grafiği";
            case "compare.section.series": return "Seans içi ROM eğrileri";
            case "compare.col.metric": return "Ölçüm";
            case "compare.col.delta": return "Fark";
            case "compare.label.session": return "Seans";
            case "compare.label.earlier": return "Daha erken seans";
            case "compare.label.later": return "Daha geç seans";
            case "compare.card.rom": return "Maks ROM: sağ {0}° / sol {1}°";
            case "compare.card.reps": return "Tekrar: {0} / {1}";
            case "compare.card.repsR": return "Sağ tekrar: {0} / {1}";
            case "compare.card.repsL": return "Sol tekrar: {0} / {1}";
            case "compare.card.comp": return "Gövde eğilme uyarısı: {0}";
            case "compare.card.strain": return "Zorlanma (pik): %{0}";
            case "compare.m.romR": return "Sağ maks ROM";
            case "compare.m.romL": return "Sol maks ROM";
            case "compare.m.romAvg": return "Ortalama ROM";
            case "compare.m.reps": return "Tamamlanan tekrar";
            case "compare.m.repsR": return "Sağ tekrar";
            case "compare.m.repsL": return "Sol tekrar";
            case "compare.m.invalid": return "Geçersiz tekrar";
            case "compare.m.assisted": return "Yardımlı tekrar";
            case "compare.m.completion": return "Hedef tamamlama";
            case "compare.m.comp": return "Gövde eğilme uyarısı";
            case "compare.m.peakStrain": return "Pik zorlanma";
            case "compare.m.meanStrain": return "Ort. zorlanma";
            case "compare.m.dtwR": return "Hareket kalitesi (sağ)";
            case "compare.m.dtwL": return "Hareket kalitesi (sol)";
            case "compare.m.quality": return "Seans kalite skoru";
            case "compare.m.duration": return "Süre";
            case "compare.m.trackJump": return "Takip sıçraması";
            case "compare.m.secondPerson": return "2. kişi olayı";
            case "compare.m.assistNear": return "Yardımlı sezgi";
            case "compare.chart.colored": return "renk = iyileşme/kötüleşme";
            case "compare.series.missing": return "Bu seanslarda ROM zaman serisi kaydı yok.";
            case "compare.series.missingOne": return "Bu seans için ROM zaman serisi yok.";
            case "compare.series.hint": return "Her seans kendi zaman ekseninde gösterilir. Altta kollar normalize süreyle üst üste karşılaştırılır.";
            case "compare.series.meta": return "Süre {0} sn · Sağ pik {1}° · Sol pik {2}° · Hedef {3}°";
            case "compare.series.target": return "Hedef {0}°";
            case "compare.series.legR": return "Sağ kol";
            case "compare.series.legL": return "Sol kol";
            case "compare.series.yAxis": return "°";
            case "compare.series.overlayTitle": return "Kol bazlı üst üste karşılaştırma (süre normalize)";
            case "compare.series.overlayR": return "Sağ kol — iki seans";
            case "compare.series.overlayL": return "Sol kol — iki seans";
            case "compare.disclaimer": return "Karar-destek özeti; teşhis değildir. Hasta verisi yalnızca cihazınızda saklanır.";
            case "detail.html.found": return "Şifreli HTML rapor hazır. Açmak için klinisyen PIN gerekir.";
            case "detail.html.missing": return "Zaman serisi grafiği kayıtlı değil; özet metrikler gösteriliyor. HTML yoksa seans bitiminde üretilir.";
            case "detail.html.needPin": return "Rapor şifreli. Klinisyen PIN girin…";
            case "detail.html.opened": return "Rapor tarayıcıda açıldı.";
            case "detail.html.openFailed": return "Rapor açılamadı. PIN’i kontrol edip tekrar deneyin.";

            // Privacy / confirm
            case "privacy.short": return "Veriler yalnızca bu cihazda saklanır; buluta gönderilmez. Görüntü kaydı tutulmaz.";
            case "privacy.consent": return "Aydınlatmayı okudum: ad/soyad, boy, yaş, seans ölçümleri ve raporlar yalnızca bu cihazda saklanacak; kamera görüntüsü işlenir ama kaydedilmez veya üçüncü tarafa gönderilmez. Silme hakkımı menüden kullanabileceğimi biliyorum.";
            case "privacy.delete.title": return "Tüm yerel veriler silinsin mi?";
            case "privacy.delete.body": return "Profil, seans geçmişi, HTML/CSV/Excel raporlar ve yüz kalibrasyonu kalıcı olarak silinir. Bu işlem geri alınamaz.";
            case "privacy.delete.yes": return "Evet, Sil";
            case "privacy.delete.no": return "Vazgeç";
            case "cam.denied.title": return "Kamera izni gerekli";
            case "cam.denied.body": return "Omuz fleksiyonu ölçümü için kamera erişimi gerekir. Görüntü cihazda işlenir; kaydedilmez. Ayarlardan izin verip tekrar deneyin.";
            case "cam.missing.title": return "Kamera bulunamadı";
            case "cam.missing.body": return "Bu cihazda kullanılabilir bir kamera yok. Kamerayı bağlayıp uygulamayı yeniden başlatın.";
            case "cam.fail.title": return "Kamera açılamadı";
            case "cam.fail.body": return "Kamera başlatılamadı. Başka bir uygulama kamerayı kullanıyor olabilir. Kapatıp tekrar deneyin.";
            case "model.fail.title": return "AI model yüklenemedi";
            case "model.fail.body": return "Pose / yüz modeli başlatılamadı. Uygulamayı yeniden başlatın. Sorun sürerse cihazın desteklenen sürümde olduğundan emin olun.";
            case "common.retry": return "Tekrar Dene";

            // Pre-session
            case "presession.title": return "Hedef Açı ve Seans Bilgileri";
            case "presession.section.patient": return "Hasta bilgisi";
            case "presession.section.targets": return "Hedefler";
            case "presession.section.arms": return "Ölçülecek kol";
            case "presession.title.profile": return "Yeni hasta kaydı";
            case "presession.profileOnly.hint": return "Açı ve tekrar ilk seansta otomatik ölçülür.\nÖnce kolunu rahatça kaldırabildiğin kadar kaldır.";
            case "presession.first": return "Ad *";
            case "presession.last": return "Soyad *";
            case "presession.height": return "Boy (cm)";
            case "presession.age": return "Yaş (isteğe bağlı)";
            case "presession.reason": return "Neden fizyoterapi (isteğe bağlı)";
            case "presession.ph.reason": return "Örn. omuz ağrısı, ameliyat sonrası — teşhis değil";
            case "presession.gender": return "Cinsiyet (avatar)";
            case "presession.male": return "Erkek (Y Bot)";
            case "presession.female": return "Kadın (X Bot)";
            case "presession.right": return "Sağ kol ölçümü";
            case "presession.left": return "Sol kol ölçümü";
            case "presession.sequential": return "Sırayla iki kol (önce sağ, sonra sol)";
            case "presession.err.armXor": return "Omuz fleksiyonu için sağ veya sol kol seçin (ikisi birden değil)";
            case "presession.sideGuide": return "Yan durun. Sağ kol → sağ omzunuzu kameraya; sol kol → sol omzunuzu kameraya gösterin.";
            case "presession.frontGuide": return "Kameraya dönük durun. Bir veya iki kolu yana (abdüksiyon) kaldırın — omuzlar ve baş kadrajda olsun.";
            case "presession.exercise.hint": return "Fleksiyon: yan profil, tek kol veya sırayla. Abdüksiyon: önden, iki kol aynı anda.";
            case "presession.personal": return "Önerilen hedefi alanlara yaz";
            case "presession.confirm": return "Hedefi Onayla ve Başlat";
            case "presession.confirm.profile": return "Hastayı Kaydet";
            case "presession.cancel": return "İptal";
            case "presession.err.consent": return "Devam için KVKK aydınlatmasını onaylayın";
            case "presession.err.name": return "Ad ve soyad zorunludur";
            case "presession.err.height": return "Geçerli bir boy girin (örn. 170)";
            case "presession.err.age": return "Yaş 1–120 arasında olmalı veya boş bırakılmalı";
            case "presession.err.gender": return "Cinsiyet seçin (avatar için)";
            case "presession.err.session": return "Boy 100–250 cm olmalı ve en az bir kol seçilmeli";
            case "presession.err.angle": return "Hedef açı 90–170° arasında olmalı";
            case "presession.err.reps": return "Hedef tekrar 1–30 arasında olmalı";
            case "presession.ph.first": return "Ad";
            case "presession.ph.last": return "Soyad";
            case "presession.target.angle": return "Hedef açı";
            case "presession.target.reps": return "Hedef tekrar";
            case "presession.target.deg": return "{0}°";
            case "presession.target.repn": return "{0}";
            case "presession.err.movement": return "Canlı seans için omuz fleksiyonu veya abdüksiyonu seçin";
            case "presession.exercise": return "Egzersiz (bölge → hareket)";

            case "exercise.region.shoulder": return "Omuz";
            case "exercise.region.arm": return "Kol";
            case "exercise.region.elbow": return "Dirsek";
            case "exercise.region.neck": return "Boyun";
            case "exercise.region.leg": return "Bacak";
            case "exercise.region.ankle": return "Ayak bileği";
            case "exercise.move.shoulder.flexion": return "Omuz fleksiyonu";
            case "exercise.move.shoulder.abduction": return "Omuz abdüksiyonu";
            case "exercise.move.shoulder.er": return "Omuz dış rotasyon";
            case "exercise.move.shoulder.ir": return "Omuz iç rotasyon";
            case "exercise.move.arm.elevation": return "Kol elevasyonu";
            case "exercise.move.arm.hadduction": return "Yatay addüksiyon";
            case "exercise.move.elbow.flexion": return "Dirsek fleksiyonu";
            case "exercise.move.elbow.extension": return "Dirsek ekstansiyonu";
            case "exercise.move.neck.flexion": return "Boyun fleksiyonu";
            case "exercise.move.neck.rotation": return "Boyun rotasyonu";
            case "exercise.move.neck.lateral": return "Boyun yana eğme";
            case "exercise.move.leg.hipFlexion": return "Kalça fleksiyonu";
            case "exercise.move.leg.hipAbduction": return "Kalça abdüksiyonu";
            case "exercise.move.ankle.dorsi": return "Ayak bileği dorsifleksiyon";
            case "exercise.move.ankle.plantar": return "Ayak bileği plantarfleksiyon";
            case "exercise.notLiveYet": return "Yakında";
            case "exercise.comingSoon": return " (yakında)";

            // HUD
            case "hud.session.active": return "● SEANS AKTİF";
            case "hud.session.done": return "Seans tamamlandı";
            case "hud.session.idle": return "Örnek hareketi izle — hazır olunca seansı başlat";
            case "hud.session.positioning": return "Önce konumunu ayarla";
            case "hud.example.hint": return "Örnek hareket";
            case "hud.btn.start": return "Seansı Başlat";
            case "hud.btn.end": return "Seansı Bitir";
            case "hud.btn.back": return "Menüye Dön";
            case "visit.plan.title": return "Bugünkü hareketler";
            case "visit.plan.current": return "Sırada";
            case "visit.plan.done": return "Tamamlandı";
            case "visit.complete.title": return "Hareket tamamlandı";
            case "visit.complete.body": return "{0} bitti ({1}/{2})";
            case "visit.complete.next": return "Sıradaki: {0}";
            case "visit.complete.continue": return "Devam";
            case "presession.queue.hint": return "Canlı harekete tıklayarak sıraya ekleyin veya çıkarın.";
            case "hud.strain": return "Zorlanma %{0}";
            case "hud.strain.est": return "Tahmini %{0}";
            case "hud.strain.noface": return "Yüz bulunamadı";
            case "hud.frame.hint": return "Gövde, omuz ve dirsek kamerada görünsün (eksik bölge hesaplanmaz)";
            case "hud.quality.reliable": return "Kalite: güvenilir";
            case "hud.quality.caution": return "Kalite: dikkat (ışık/kıyafet/mesafe)";
            case "hud.quality.invalid": return "Kalite: düşük — zirve ROM güvenilmez";
            case "hud.assist": return "Yardım aktif";
            case "hud.assist.on": return "Yardım AÇIK";
            case "hud.assist.auto": return "Temas+hız → yardım";
            case "hud.assist.secondPerson": return "2. kişi sahnede";
            case "hud.rep.right": return "Sağ:";
            case "hud.rep.left": return "Sol:";
            case "hud.rom.arm.right": return "SAĞ KOL";
            case "hud.rom.arm.left": return "SOL KOL";
            case "hud.rom.detail": return "Hedef {0}°  ·  Kalan {1}°  ·  %{2}";
            case "hud.upright": return "Dik duruş sapması: {0}°";
            case "hud.upright.yaw": return "Dönüş: {0}°";
            case "hud.posture.upright.good": return "Dik oturuş iyi ({0}°)";
            case "hud.posture.upright.warn": return "Biraz daha dik otur ({0}°)";
            case "hud.posture.upright.bad": return "Gövdeni dik tut ({0}° — eşik aşıldı)";
            case "hud.posture.facing.good": return "Kameraya bakış iyi (dönüş {0}°)";
            case "hud.posture.facing.warn": return "Biraz daha kameraya dön ({0}°)";
            case "hud.posture.facing.bad": return "Kameraya tam önden bak (dönüş {0}°)";
            case "hud.posture.facing.missing": return "Gövde ve yüz kamerada tam görünsün";
            case "hud.posture.sideOk": return "Yan kamera: profil protokolü";
            case "pos.step.title": return "Adım 1 / 2 — Konumunu ayarla";
            case "pos.hint.faceCamera": return "Yan durun — omuzlar ve baş kadrajda olsun";
            case "pos.hint.center": return "Ortadaki alana geç ve biraz sabit kal";
            case "pos.hint.moveLeft": return "← Biraz sola kay";
            case "pos.hint.moveRight": return "Biraz sağa kay →";
            case "pos.hint.holdGreen": return "Mükemmel! Bu konumda sabit kal";
            case "pos.hint.head": return "Başınız kadrajda görünsün";
            case "pos.hint.sideMore": return "Daha yana dönün (omuzlar dar görünsün)";
            case "pos.hint.sideWrong": return "Çalışan omzunuzu kameraya çevirin";
            case "pos.hint.sideOk": return "Yan profil iyi — sabit kalın";
            case "warn.sideSkew": return "Daha yana dönün — ölçüm için yan profil gerekli";
            case "warn.sideInvalid": return "Yan profil bozuldu — bu kare ölçüme alınmadı";
            case "warn.headFrame": return "Başınızı kadraja alın";
            case "warn.wrongSide": return "Yanlış yan: çalışan omzu kameraya gösterin";
            case "hud.phase": return "Faz {0}/2 — {1}";
            case "hud.phase.right": return "Sağ kol";
            case "hud.phase.left": return "Sol kol";
            case "report.protocol.side": return "Yan profil (omuz fleksiyonu)";
            case "report.protocol.front": return "Ön profil (omuz abdüksiyonu)";
            case "report.protocol.sequential": return "Sırayla iki kol";
            case "pos.countdown.subtitle": return "Örneği izle — hazır olunca seansı başlat";
            case "pos.skip.btn": return "Konumu atla (test)";
            case "hud.pos.skip.on": return "Konumu kapat";
            case "hud.pos.skip.off": return "Konumu aç";

            // Warnings / coach
            case "warn.stand": return "Gövdeni dik tut";
            case "warn.faceFront": return "Kameranın karşısına geç — omuzların görünsün";
            case "warn.turnFront": return "Kameranın karşısına geç — omuzların görünsün";
            case "warn.depthCollapse": return "Kolunu kameraya doğru düz uzatma — yana-yukarı aç (ölçüm için görünür kalsın)";
            case "warn.strain": return "ZORLANMA YÜKSEK";
            case "warn.repInvalid": return "TEKRAR SAYILMADI - Dik dur!";
            case "warn.trackingJump": return "KADRAJ / TAKİP SİÇRADI — Kamerayı sabitleyin";
            case "warn.secondPerson": return "SAHNEDE 2. KİŞİ — Yardım ölçümü gündeme gelebilir";
            case "warn.assistNear": return "YARDIMLI ÖLÇÜM — El temas + eş yönlü hız";
            case "coach.sessionStart": return "Seans başlıyor. Kolunu yana-yukarı kontrollü kaldır; kameraya doğru düz uzatma.";
            case "coach.stand": return "Kolunu kaldırırken gövdeni yana eğme; sırtını dik tut.";
            case "coach.faceFront": return "Kameranın karşısına geç; omuzların görünsün.";
            case "coach.turnFront": return "Kameranın karşısına geç; omuzların görünsün.";
            case "coach.depthCollapse": return "Kolunu kameraya doğru düz uzatma. Yana ve yukarı kaldır.";
            case "coach.strain": return "Zorlanma yüksek. Tempo yavaşlat, nefes al.";
            case "coach.repInvalid": return "Tekrar sayılmadı. Dik durup yeniden dene.";
            case "coach.slow": return "Daha yavaş kaldır. Kontrolü kaybetme.";
            case "coach.pace": return "Güzel tempo. Böyle devam.";
            case "coach.almost": return "Hedefe yaklaştın. Son tekrarlara dikkat.";
            case "coach.targets": return "Bugünkü hedefin {0} derece, {1} tekrar. Düzgün duruşla, kontrollü kaldır.";
            case "target.default": return "Varsayılan hedefler";
            case "target.hard": return "Öneri: {0}° / {1} tekrar (önceki seans zorlu)";
            case "target.ok": return "Öneri: {0}° / {1} tekrar (önceki ROM {2}°)";

            // Report HTML
            case "report.title": return "Fizyoterapi Seans Raporu";
            case "report.session": return "Seans";
            case "report.rightMax": return "Sağ Maks ROM";
            case "report.leftMax": return "Sol Maks ROM";
            case "report.rightAvg": return "Sağ Ort ROM";
            case "report.leftAvg": return "Sol Ort ROM";
            case "report.rightReps": return "Sağ Tekrar";
            case "report.leftReps": return "Sol Tekrar";
            case "report.targetAngle": return "Hedef Açı";
            case "report.compensation": return "Kompansasyon";
            case "report.duration": return "Süre";
            case "report.peakStrain": return "Pik Zorlanma";
            case "report.meanStrain": return "Ort Zorlanma";
            case "report.quality.mean": return "Kalite skoru (ort)";
            case "report.quality.band": return "Kalite bandı";
            case "report.quality.reliable": return "Güvenilir";
            case "report.quality.caution": return "Dikkat";
            case "report.quality.invalid": return "Düşük / geçersiz";
            case "report.quality.unknown": return "Bilinmiyor";
            case "report.series.right": return "Sağ kol";
            case "report.series.left": return "Sol kol";
            case "report.patient": return "Hasta";
            case "report.invalid": return "geçersiz";
            case "report.arms.both": return "Sağ + Sol";
            case "report.arms.right": return "Sağ";
            case "report.arms.left": return "Sol";
            case "report.progress.title": return "İlerleme Raporu";
            case "report.progress.chart": return "Seanslar Arası ROM Gelişimi";
            case "report.progress.history": return "Seans Geçmişi";
            case "report.progress.clickHint": return "Tablo satırına veya grafik noktasına tıklayarak seans özetini açın.";
            case "stats.title": return "İlerleme istatistikleri (PS-1.1)";
            case "stats.sessions": return "Seans sayısı";
            case "report.assisted.right": return "Yardımlı tekrar (sağ)";
            case "report.assisted.left": return "Yardımlı tekrar (sol)";
            case "report.assisted.total": return "Yardımlı tekrar (toplam)";
            case "detail.note.assisted": return "• Yardımlı tekrar: {0} (bağımsız {1}).";
            case "detail.note.trackingJump": return "• Takip/kadraj sıçraması: {0} olay — ROM güvenilirliği düşmüş olabilir.";
            case "detail.note.secondPerson": return "• Sahnede 2. kişi: {0} olay (manuel yardım kapalı olsa da not edilir).";
            case "detail.note.assistNear": return "• Yardımlı sezgi (temas + hız vektörü + süreğenlik): {0} olay.";
            case "report.trackingJump": return "Takip sıçraması";
            case "report.secondPerson": return "2. kişi sahnede";
            case "report.assistNear": return "Yardımlı sezgi";
            case "stats.romTrend": return "ROM trendi (ilk→son)";
            case "stats.romTrendRight": return "Sağ ROM trendi";
            case "stats.romTrendLeft": return "Sol ROM trendi";
            case "stats.completion": return "Ort. tamamlanma";
            case "stats.invalidRate": return "Geçersiz tekrar oranı";
            case "stats.assistedRate": return "Yardımlı tekrar oranı";
            case "stats.repsIndep": return "Bağımsız tekrar (toplam)";
            case "stats.repsAssisted": return "Yardımlı tekrar (toplam)";
            case "stats.sessionsWeek": return "Gözlenen seans/hafta";
            case "stats.plannedWeek": return "Planlanan seans/hafta";
            case "stats.adherence": return "Uyum (adherence)";
            case "stats.meanRom": return "Ort. maks ROM";
            case "stats.qwMeanRom": return "Kalite ağırlıklı ort. ROM";
            case "stats.meanQuality": return "Ort. kalite skoru";
            case "stats.meanPeakStrain": return "Ort. pik zorlanma";
            case "stats.compSessions": return "Kompansasyonlu seans";
            case "stats.eventsComp": return "Kompansasyon olayları";
            case "stats.eventsJump": return "Takip sıçraması";
            case "stats.eventsSecond": return "2. kişi olayları";
            case "stats.eventsAssistNear": return "Yardım yakınlığı";
            case "stats.formula": return "Formül sürümü";
            case "stats.note": return "Özet tüm dışa aktarılan seanslar üzerinden hesaplanır; aşağıdaki filtre yalnız tablo/grafik içindir. Karar-destek; teşhis değildir.";
            case "report.progress.axisHint": return "Dikey eksen: açı (°). Yatay eksen: seans numarası (gerekirse 5 / 10 / 15 / 20 / 30 adımlı).";
            case "report.progress.xAxis": return "Seans no";
            case "report.progress.yAxis": return "Açı (°)";
            case "report.metrics": return "Metrikler:";
            case "report.maxRom": return "Maks ROM";
            case "report.avgRom": return "Ort ROM";
            case "report.col.date": return "Tarih";
            case "report.col.validTarget": return "Geçerli/Hedef";
            case "report.col.invalid": return "Geçersiz";
            case "report.col.strain": return "Zorlanma";
            case "report.firstMax": return "İlk Maks ROM";
            case "report.lastMax": return "Son Maks ROM";
            case "report.change": return "Değişim";
            case "report.disclaimer": return "Bu rapor klinik karar destek amaçlıdır; teşhis yerine geçmez. Değerlendirme klinisyen tarafından yapılmalıdır. Kişisel veriler yalnızca yerel cihaz üzerindedir.";
            case "report.disclaimer.short": return "Bu rapor klinik karar destek amaçlıdır; teşhis yerine geçmez.";
            case "report.notes": return "Klinik Notlar";
            case "report.survey.btn": return "Klinisyen: seans sonrası yanıtlar";
            case "report.survey.btn.hide": return "Yanıtları gizle";
            case "report.survey.title": return "Seans sonrası özbildirim";
            case "report.survey.hint": return "Varsayılan olarak gizli. Yalnızca klinisyen açar. Teşhis değildir.";
            case "report.survey.col.q": return "Soru";
            case "report.survey.col.a": return "Yanıt";
            case "report.survey.none": return "Bu seans için kayıtlı anket yok.";
            case "face.btn": return "Yüz Kalibrasyonu";
            case "face.title": return "Yüz Zorlanma Kalibrasyonu";
            case "face.hint": return "Önce 15 sn rahat yüz, sonra 60 sn zorlanma ifadeleri (kaş çatma, göz kısma, diş sıkma).\nHam video kaydedilmez.";
            case "face.ready": return "Hazır — Başlat'a basın";
            case "face.start": return "Kalibrasyonu Başlat";
            case "face.skip": return "Atla (eski yöntem)";
            case "face.cancel": return "İptal";
            case "face.rest.title": return "1/2 — Rahat yüz";
            case "face.rest.hint": return "Kameraya bakın, yüzünüzü gevşetin. Konuşmayın, kaş çatmayın.";
            case "face.rest.progress": return "Rest {0} · örnek {1}";
            case "face.strain.title": return "2/2 — Zorlanma ifadeleri (~1 dk)";
            case "face.strain.hint": return "Zorlanırken yaptığınız yüzleri gösterin: kaş çatma, göz kısma, diş/dudak sıkma, burun buruşturma. Çeşitli tekrarlayın.";
            case "face.strain.progress": return "Strain {0} · örnek {1}";
            case "face.noface": return " — yüz bulunamadı";
            case "face.saved": return "Kalibrasyon kaydedildi.";
            case "report.person": return "Kişi Bilgileri";
            case "report.name": return "Ad Soyad";
            case "report.reasonForCare": return "Neden fizyoterapi";
            case "report.height": return "Boy";
            case "report.age": return "Yaş";
            case "report.gender": return "Cinsiyet";
            case "report.arms": return "Ölçülen kol";
            case "report.movement": return "Hareket";
            case "report.protocol": return "Protokol";
            case "report.sessionNo": return "Seans no";
            case "report.date": return "Tarih";
            case "report.male": return "Erkek";
            case "report.female": return "Kadın";
            case "common.yes": return "Evet";
            case "common.no": return "Hayır";

            case "menu.btn.program": return "Programım";
            case "menu.btn.notes": return "Hasta Notları";
            case "menu.btn.clinician": return "Klinisyen Girişi";
            case "notes.title": return "Hasta Not Defteri";
            case "notes.patient": return "Hasta: {0}";
            case "notes.noPatient": return "Aktif hasta seçili değil";
            case "notes.path": return "Dosya: {0}";
            case "notes.placeholder": return "Klinik gözlem, ev egzersizi notları, uyarılar…";
            case "notes.btn.save": return "Kaydet";
            case "notes.btn.reload": return "Yenile";
            case "notes.btn.openFile": return "Dosyayı Aç";
            case "notes.btn.close": return "Kaydet ve Çık";
            case "notes.saved": return "Notlar kaydedildi.";
            case "notes.saveFailed": return "Kayıt başarısız.";
            case "notes.reloaded": return "Dosyadan yeniden yüklendi.";
            case "notes.openedExternal": return "Notepad / varsayılan uygulama açıldı.";
            case "notes.openFailed": return "Dosya açılamadı.";
            case "picker.title": return "Hasta seç";
            case "picker.hint": return "Arayın veya son hastalardan seçin. Yanlış hasta seçimini önlemek için onaylayın.";
            case "picker.searchPh": return "Ad veya soyad ara…";
            case "picker.recent": return "Son kullanılanlar";
            case "picker.all": return "Tüm hastalar";
            case "picker.results": return "Arama sonuçları";
            case "picker.empty": return "Kayıtlı hasta bulunamadı. Yeni hasta ekleyin.";
            case "picker.new": return "+ Yeni hasta";
            case "picker.confirmTitle": return "Hasta onayı";
            case "picker.confirmBody": return "Bu seans: {0}?";
            case "picker.confirmContinue": return "Devam et";
            case "picker.confirmBack": return "Geri";
            case "picker.active": return "Aktif hasta: {0}";
            case "picker.activeNone": return "Aktif hasta seçilmedi";
            case "picker.yearsSuffix": return " yaş";
            case "picker.sessions": return "{0} seans";
            case "picker.change": return "Hasta değiştir";
            case "picker.edit": return "Bilgileri düzenle";

            case "presession.title.edit": return "Hasta bilgilerini düzenle";
            case "presession.confirm.edit": return "Değişiklikleri Kaydet";
            case "assess.banner": return "Tanıma seansı {0}/{1}";
            case "assess.live.start": return "ROM analizi: kolunu kaldırabildiğin kadar kaldır";
            case "assess.live.measuring": return "Analiz…";
            case "assess.live.ready": return "Hedef {0}° · slider dolu ≈ {1}° — tekrarlara geç!";
            case "survey.title.assess": return "Tanıma anketi ({0}/{1})";
            case "survey.title.checkin": return "Seans sonrası kısa check-in";
            case "survey.hint": return "0 kötü, 5 nötr, 10 iyi. Bilmiyorsanız “Bilmiyorum”a basın. Teşhis değildir.";
            case "survey.progress": return "Soru {0}/{1}";
            case "survey.next": return "Sonraki";
            case "survey.unknown": return "Bilmiyorum";
            case "survey.q.difficulty": return "Bu seansı ne kadar kolay buldunuz? (0 çok zor – 10 çok kolay)";
            case "survey.q.pain": return "Seans sırasında ne kadar rahattınız? (0 şiddetli ağrı – 10 ağrı yok)";
            case "survey.q.motivation": return "Motivasyonunuz? (0 düşük – 10 yüksek)";
            case "survey.q.fatigue": return "Ne kadar dinç hissediyorsunuz? (0 bitkin – 10 çok dinç)";
            case "survey.q.homeDays": return "Son 7 günde evde egzersiz günü? (0 hiç – 7 her gün)";
            case "survey.q.sleep": return "Uyku kalitesi? (0 kötü – 10 iyi)";
            case "survey.q.confidence": return "Hareketi doğru yaptığınıza güven? (0 düşük – 10 yüksek)";
            case "survey.q.willingness": return "Yarına devam isteği? (0 yok – 10 çok istekli)";
            case "careplan.title": return "Antrenman programım";
            case "careplan.empty": return "Henüz program yok. Tanıma seanslarını tamamlayın.";
            case "careplan.forPatient": return "Hasta: {0}";
            case "careplan.phase.assess": return "Tanıma dönemi";
            case "careplan.phase.active": return "Aktif program";
            case "careplan.assess.progress": return "Tanıma devam ediyor: {0} / {1} seans tamamlandı.\n\nProgram, 5. seans sonrası otomatik oluşturulur.";
            case "careplan.summary.default": return "Başlangıç programı (temkinli).";
            case "careplan.summary.cautious": return "Temkinli plan: {0}° / {1} tekrar, haftada {2} seans.";
            case "careplan.summary.progress": return "İlerleme planı: {0}° / {1} tekrar, haftada {2} seans.";
            case "careplan.summary.deload": return "Yük azaltıldı (deload): {0}° / {1} tekrar.";
            case "careplan.section.todayTarget": return "Bugünkü hedef";
            case "careplan.section.week": return "Bu hafta";
            case "careplan.section.month": return "Aylık plan";
            case "careplan.metric.angle": return "Hedef açı";
            case "careplan.metric.reps": return "Tekrar";
            case "careplan.metric.sessionsWeek": return "Seans / hafta";
            case "careplan.metric.intensity": return "Yoğunluk";
            case "careplan.daily": return "Günlük hedef: {0}° · {1} tekrar";
            case "careplan.weekly": return "Haftalık: {0} seans · yoğunluk: {1}";
            case "careplan.today.train": return "Bugün antrenman günü";
            case "careplan.today.rest": return "Bugün dinlenme / hafif gün";
            case "careplan.monthly.title": return "Aylık iskelet:";
            case "careplan.monthly.week": return "  Hafta {0}: {1}° / {2} tekrar ({3})";
            case "careplan.monthly.weekClean": return "Hafta {0}   ·   {1}°   ·   {2} tekrar   ·   {3}";
            case "careplan.intensity.easy": return "kolay";
            case "careplan.intensity.standard": return "standart";
            case "careplan.intensity.deload": return "deload";
            case "careplan.presession.fromPlan": return "Programdan: {0}° / {1} tekrar";
            case "clinician.title": return "Klinisyen erişimi";
            case "clinician.enterPin": return "PIN girin (yalnızca klinisyen)";
            case "clinician.setPin": return "İlk kurulum: 4–8 haneli PIN belirleyin";
            case "clinician.unlock": return "Kilidi aç / Rapor";
            case "clinician.unlockHtml": return "PIN ile aç";
            case "clinician.pinForReport": return "Şifreli raporlara erişmek için PIN girin";
            case "clinician.inapp.patient": return "Hasta: {0}";
            case "clinician.inapp.reason": return "Neden FT: {0}";
            case "clinician.inapp.noPatient": return "Aktif hasta seçili değil";
            case "clinician.inapp.phase.assess": return "Tanıma dönemi — {0}/{1} seans";
            case "clinician.inapp.phase.active": return "Aktif program (sürüm {0})";
            case "clinician.inapp.plan": return "Hedef {0}° / {1} tekrar · haftada {2} seans · son uyarlama: {3}";
            case "clinician.inapp.sessions": return "Kayıtlı seans: {0}";
            case "clinician.inapp.note.header": return "Seans #{0} · {1} · {2}";
            case "clinician.inapp.note.claim": return "Hasta ifadesi: {0}";
            case "clinician.inapp.note.obs": return "Gözlem: {0}";
            case "clinician.err.format": return "PIN 4–8 rakam olmalıdır";
            case "clinician.err.pin": return "PIN hatalı";
            case "clinician.showPin": return "Şifreyi göster";
            case "clinician.hidePin": return "Şifreyi gizle";
            case "clinician.report.title": return "Klinisyen karar-destek raporu";
            case "clinician.report.phase": return "Faz";
            case "clinician.report.plan": return "Güncel plan";
            case "clinician.report.sessions": return "Seans özeti";
            case "clinician.report.notes": return "Uyumsuzluk notları (hasta görmez)";
            case "clinician.report.noNotes": return "Kayıtlı uyumsuzluk notu yok.";
            case "clinician.report.disclaimer": return "Bu rapor klinik karar-destek amaçlıdır; teşhis veya tedavi planı yerine geçmez. Notlar yalnızca klinisyen erişimine açıktır.";
            case "clinician.claim.easy": return "Seans kolay bulundu ({0}/10)";
            case "clinician.claim.hard": return "Seans zor bulundu ({0}/10)";
            case "clinician.claim.noPain": return "Ağrı yok bildirildi ({0}/10 rahatlık)";
            case "clinician.claim.dailyHome": return "Ev egzersizi {0} gün/hafta bildirildi";
            case "clinician.obs.strain": return "Pik zorlanma %{0}, kompansasyon {1}, geçersiz {2}";
            case "clinician.obs.comp": return "Kompansasyon {0}, geçersiz tekrar {1}";
            case "clinician.obs.lowLoad": return "Tamamlanma %{0}, düşük zorlanma %{1}, kompansasyon yok";
            case "clinician.obs.frequency": return "Uygulama seans sıklığı ~{0}/hafta";
            case "vault.enterPin": return "Hasta rapor klasörü kilitli — klinisyen PIN girin";
            case "vault.unlock": return "Kilidi aç";
            case "vault.openFailed": return "Rapor açılamadı. PIN ile kilit açın.";
            case "vault.lockedHint": return "Her hasta ayrı klasörde (şifreli). Açmak için doktor PIN gerekir.";
            case "vault.migrated": return "{0} eski rapor hasta klasörüne taşındı.";

            default: return key;
        }
    }

    private static string En(string key)
    {
        switch (key)
        {
            case "menu.subtitle": return "Local data · Privacy: delete anytime from menu";
            case "menu.session.idle": return "Waiting for session";
            case "menu.session.active": return "SESSION ACTIVE";
            case "menu.session.done": return "Last session completed";
            case "menu.card.rom": return "Last Max ROM";
            case "menu.card.completion": return "Progress %";
            case "menu.card.compensation": return "Last Compensation";
            case "menu.graph.title": return "ROM progress across sessions";
            case "menu.graph.legend": return "Mint: R max · Blue: L max · Purple: Strain";
            case "menu.history.title": return "Session history — tap Detail";
            case "menu.history.loading": return "Loading…";
            case "menu.history.empty": return "No sessions yet.\nStart an exercise to create the first session.";
            case "menu.btn.start": return "Start Exercise";
            case "menu.btn.html": return "Open Progress Report";
            case "menu.btn.compare": return "Compare Sessions";
            case "menu.btn.folder": return "Reports Folder";
            case "menu.btn.refresh": return "Refresh";
            case "menu.btn.delete": return "Delete My Data";
            case "menu.btn.lang": return "Türkçe";
            case "menu.hist.session": return "Session";
            case "menu.hist.sessionN": return "Session {0}";
            case "menu.hist.rightRom": return "R:";
            case "menu.hist.leftRom": return "L:";
            case "menu.hist.reps": return "reps";
            case "menu.hist.invalid": return "invalid";
            case "menu.hist.compensation": return "Compensation";
            case "menu.hist.strainPeak": return "Peak strain";
            case "side.right": return "Right";
            case "side.left": return "Left";
            case "side.right.abbr": return "R";
            case "side.left.abbr": return "L";
            case "menu.hist.dtw.right": return "DTW R";
            case "menu.hist.dtw.left": return "DTW L";
            case "menu.card.progress": return "Progress %";
            case "menu.toggle.right": return "R max";
            case "menu.toggle.left": return "L max";
            case "menu.toggle.avg": return "Avg";
            case "menu.toggle.strain": return "Strain";
            case "filter.all": return "All";
            case "filter.week": return "Last 7 days";
            case "filter.month": return "Last 30 days";
            case "filter.quarter": return "Last 90 days";
            case "filter.last5": return "Last 5 sessions";
            case "filter.last10": return "Last 10 sessions";
            case "filter.last20": return "Last 20 sessions";
            case "filter.withComp": return "With compensation";
            case "filter.noComp": return "No compensation";
            case "filter.highStrain": return "High strain (≥55%)";
            case "filter.incomplete": return "Target incomplete";
            case "filter.rightArm": return "R arm measured";
            case "filter.leftArm": return "L arm measured";
            case "filter.exercise": return "Movement";
            case "filter.region.shoulder": return "Shoulder";
            case "filter.region.arm": return "Arm";
            case "filter.region.elbow": return "Elbow";
            case "filter.region.neck": return "Neck";
            case "filter.region.leg": return "Leg";
            case "filter.region.ankle": return "Ankle";
            case "filter.move.shoulderFlexion": return "Shoulder flexion";
            case "filter.move.shoulderAbduction": return "Shoulder abduction";
            case "filter.label": return "Quality";
            case "filter.date": return "Period";
            case "filter.quality": return "Quality";
            case "progress.need2": return "≥2 sessions";
            case "progress.split": return "R:{0}  L:{1}";
            case "progress.rightOnly": return "R {0}";
            case "progress.leftOnly": return "L {0}";
            case "progress.combined": return "{0}";
            case "hud.graph.right": return "R";
            case "hud.graph.left": return "L";
            case "hud.graph.strain": return "Strain";
            case "report.col.rightMax": return "R Max";
            case "report.col.leftMax": return "L Max";
            case "report.col.rightReps": return "R Reps";
            case "report.col.leftReps": return "L Reps";
            case "report.col.invalidRL": return "Invalid R/L";
            case "report.progress.r": return "Progress R";
            case "report.progress.l": return "Progress L";
            case "report.ui.maxSplit": return "R max: {0}°   L max: {1}°";
            case "report.ui.avgSplit": return "R avg: {0}°   L avg: {1}°";
            case "report.ui.duration": return "Duration: {0}:{1}";
            case "report.ui.repsSplit": return "R: {0}/{1} (invalid {2})   L: {3}/{4} (invalid {5})";
            case "report.ui.repsOnly": return "R: {0}   L: {1}";
            case "report.ui.dtwPrefix": return "Movement match (DTW): ";
            case "report.ui.dtwSuffix": return " — vs target movement template.";
            case "report.filter": return "Filter:";
            case "report.sessions.count": return "Sessions";

            case "menu.hist.tapHint": return "Tap the row or Detail";
            case "menu.hist.detail": return "Detail";
            case "detail.title": return "Session Detail";
            case "detail.metrics": return "R max {0}° · L max {1}° · Target {2}°\nReps {3}/{4} · Compensation {5} · Peak strain %{6}\nDTW R %{7} · DTW L %{8}";
            case "detail.box.rom": return "<b>Range of motion (ROM)</b>\nRight shoulder peak: {0}°\nLeft shoulder peak: {1}°\nSession target angle: {2}°";
            case "detail.box.session": return "<b>Session summary</b>\nCompleted reps: {0} / {1}\nCompensation alerts: {2}\nPeak strain: %{3}";
            case "detail.box.quality": return "<b>Movement quality (DTW)</b>\nRight arm similarity: %{0}\nLeft arm similarity: %{1}\n(100 = close to target template)";
            case "detail.note.dtwBoth": return "• Movement quality (DTW): R %{0}, L %{1}.";
            case "detail.note.dtwRight": return "• Movement quality (DTW) R: %{0}.";
            case "detail.note.dtwLeft": return "• Movement quality (DTW) L: %{0}.";
            case "menu.hist.dtw": return "DTW";
            case "detail.chart.legend": return "Mint = right · Blue = left · Orange = target · Purple = strain · Red = assisted · X = time (s)";
            case "detail.chart.noSeries": return "No time series in this record (older session). Open the HTML report for the full chart.";
            case "detail.summary.title": return "AI report summary";
            case "detail.summary.header": return "Clinical decision-support summary (rule-based):";
            case "detail.summary.empty": return "No summary could be generated for this session.";
            case "detail.summary.disclaimer": return "This is not a diagnosis; it is a local summary to support the physiotherapist.";
            case "detail.note.rightOnly": return "• Measurement focused on the R arm.";
            case "detail.note.leftOnly": return "• Measurement focused on the L arm.";
            case "detail.note.bothArms": return "• R and L arm measurements available.";
            case "detail.note.noReps": return "• No valid reps recorded or session incomplete.";
            case "detail.note.targetRepsMet": return "• Target rep count was reached.";
            case "detail.note.targetRepsPct": return "• About {0}% of target reps completed.";
            case "detail.note.romMet": return "• Max ROM reached or exceeded the target angle.";
            case "detail.note.romBelow": return "• Max ROM stayed about {0}° below target.";
            case "detail.note.noComp": return "• You kept your trunk upright; you did not lean sideways to lift your arm.";
            case "detail.note.mildComp": return "• A few times ({0}) you leaned your trunk sideways to lift your arm. Try to keep your trunk still.";
            case "detail.note.highComp": return "• Often ({0} times) you leaned sideways to lift your arm. Next session, focus on keeping your trunk upright.";
            case "detail.note.invalid": return "• Invalid reps: {0}.";
            case "detail.note.highStrain": return "• High strain (peak %{0}) near R {1}° / L {2}°.";
            case "detail.note.strainOk": return "• Strain within a moderate range (peak %{0}, mean %{1}).";
            case "detail.note.quality": return "• Session quality ({0}): mean %{1}.";
            case "detail.note.romUp": return "• Max ROM about +{0}° vs previous session.";
            case "detail.note.romDown": return "• Max ROM about −{0}° vs previous session.";
            case "detail.note.romFlat": return "• ROM similar to the previous session.";
            case "detail.note.strainUp": return "• Strain up about +%{0} vs previous session.";
            case "detail.note.strainDown": return "• Strain down about −%{0} vs previous session.";
            case "detail.btn.back": return "Back";
            case "detail.btn.html": return "Open Session Report";
            case "detail.btn.survey": return "Clinician: survey";
            case "detail.btn.compare": return "Compare with another session";
            case "detail.btn.openPrev": return "Open previous session";
            case "detail.compare.title": return "This session ↔ Previous session";
            case "detail.compare.none": return "No previous session to compare.";
            case "detail.compare.current": return "This session";
            case "detail.compare.previous": return "Previous session";
            case "detail.compare.rom": return "Max ROM\nR {0}° · L {1}°";
            case "detail.compare.reps": return "Reps\n{0} / {1}";
            case "detail.compare.comp": return "Trunk lean alerts\n{0} times";
            case "detail.compare.strain": return "Strain\n%{0}";
            case "detail.compare.dtw": return "Movement quality\nR %{0} · L %{1}";
            case "detail.compare.deltaRom": return "ROM change: {0}";
            case "detail.compare.deltaComp": return "Lean-alert change: {0}";
            case "detail.compare.close": return "Close comparison";
            case "compare.picker.title": return "Compare sessions";
            case "compare.picker.hint": return "Pick two sessions. The report is generated instantly as HTML (not after every session).";
            case "compare.picker.slotAEmpty": return "A: not selected — tap a row";
            case "compare.picker.slotBEmpty": return "B: not selected — tap a row";
            case "compare.picker.slotA": return "A: {0}";
            case "compare.picker.slotB": return "B: {0}";
            case "compare.picker.rowSub": return "R {0}° · L {1}° · Lean {2}";
            case "compare.picker.empty": return "No sessions to compare.";
            case "compare.picker.generate": return "Generate HTML report";
            case "compare.picker.ready": return "Ready — report opens after PIN.";
            case "compare.picker.needTwo": return "Select two different sessions to continue.";
            case "compare.picker.needData": return "Data manager not found.";
            case "compare.report.title": return "Session comparison report";
            case "compare.legend.better": return "Improvement";
            case "compare.legend.worse": return "Worsening / attention";
            case "compare.legend.same": return "Similar";
            case "compare.section.metrics": return "All metrics";
            case "compare.section.bars": return "Comparison chart";
            case "compare.section.series": return "In-session ROM curves";
            case "compare.col.metric": return "Metric";
            case "compare.col.delta": return "Delta";
            case "compare.label.session": return "Session";
            case "compare.label.earlier": return "Earlier session";
            case "compare.label.later": return "Later session";
            case "compare.card.rom": return "Max ROM: R {0}° / L {1}°";
            case "compare.card.reps": return "Reps: {0} / {1}";
            case "compare.card.repsR": return "Right reps: {0} / {1}";
            case "compare.card.repsL": return "Left reps: {0} / {1}";
            case "compare.card.comp": return "Trunk lean alerts: {0}";
            case "compare.card.strain": return "Strain (peak): %{0}";
            case "compare.m.romR": return "Right max ROM";
            case "compare.m.romL": return "Left max ROM";
            case "compare.m.romAvg": return "Average ROM";
            case "compare.m.reps": return "Completed reps";
            case "compare.m.repsR": return "Right reps";
            case "compare.m.repsL": return "Left reps";
            case "compare.m.invalid": return "Invalid reps";
            case "compare.m.assisted": return "Assisted reps";
            case "compare.m.completion": return "Target completion";
            case "compare.m.comp": return "Trunk lean alerts";
            case "compare.m.peakStrain": return "Peak strain";
            case "compare.m.meanStrain": return "Mean strain";
            case "compare.m.dtwR": return "Movement quality (R)";
            case "compare.m.dtwL": return "Movement quality (L)";
            case "compare.m.quality": return "Session quality score";
            case "compare.m.duration": return "Duration";
            case "compare.m.trackJump": return "Tracking jumps";
            case "compare.m.secondPerson": return "2nd-person events";
            case "compare.m.assistNear": return "Assisted cue";
            case "compare.chart.colored": return "color = better/worse";
            case "compare.series.missing": return "No ROM time-series stored for these sessions.";
            case "compare.series.missingOne": return "No ROM time-series for this session.";
            case "compare.series.hint": return "Each session uses its own time axis. Below, arms are overlaid on normalized duration.";
            case "compare.series.meta": return "Duration {0} s · R peak {1}° · L peak {2}° · Target {3}°";
            case "compare.series.target": return "Target {0}°";
            case "compare.series.legR": return "Right arm";
            case "compare.series.legL": return "Left arm";
            case "compare.series.yAxis": return "°";
            case "compare.series.overlayTitle": return "Per-arm overlay (normalized duration)";
            case "compare.series.overlayR": return "Right arm — both sessions";
            case "compare.series.overlayL": return "Left arm — both sessions";
            case "compare.disclaimer": return "Decision-support summary; not a diagnosis. Patient data stays on this device only.";
            case "detail.html.found": return "Encrypted HTML report ready. Clinician PIN required to open.";
            case "detail.html.missing": return "No time-series curve is stored; summary metrics are shown. HTML is created when a session ends.";
            case "detail.html.needPin": return "Report is encrypted. Enter clinician PIN…";
            case "detail.html.opened": return "Report opened in the browser.";
            case "detail.html.openFailed": return "Could not open report. Check PIN and try again.";

            case "privacy.short": return "Data stays on this device only; not sent to the cloud. No video is recorded.";
            case "privacy.consent": return "I have read the notice: name, height, age, session measurements and reports stay on this device only; camera frames are processed but not saved or shared with third parties. I can delete my data from the menu.";
            case "privacy.delete.title": return "Delete all local data?";
            case "privacy.delete.body": return "Profile, session history, HTML/CSV/Excel reports and face calibration will be permanently deleted. This cannot be undone.";
            case "privacy.delete.yes": return "Yes, Delete";
            case "privacy.delete.no": return "Cancel";
            case "cam.denied.title": return "Camera permission required";
            case "cam.denied.body": return "Camera access is required for shoulder flexion measurement. Frames are processed on-device; not saved. Grant permission in settings and retry.";
            case "cam.missing.title": return "Camera not found";
            case "cam.missing.body": return "No usable camera on this device. Connect a camera and restart the app.";
            case "cam.fail.title": return "Could not open camera";
            case "cam.fail.body": return "Camera failed to start. Another app may be using it. Close it and retry.";
            case "model.fail.title": return "AI model failed to load";
            case "model.fail.body": return "Pose / face model could not start. Restart the app. If it persists, check device support.";
            case "common.retry": return "Retry";

            case "presession.title": return "Target Angle & Session Details";
            case "presession.section.patient": return "Patient details";
            case "presession.section.targets": return "Targets";
            case "presession.section.arms": return "Arm to measure";
            case "presession.title.profile": return "New patient registration";
            case "presession.profileOnly.hint": return "Angle and reps are measured in the first session.\nFirst lift your arm as far as you comfortably can.";
            case "presession.first": return "First name *";
            case "presession.last": return "Last name *";
            case "presession.height": return "Height (cm)";
            case "presession.age": return "Age (optional)";
            case "presession.reason": return "Why physiotherapy (optional)";
            case "presession.ph.reason": return "e.g. shoulder pain, post-op — not a diagnosis";
            case "presession.gender": return "Gender (avatar)";
            case "presession.male": return "Male (Y Bot)";
            case "presession.female": return "Female (X Bot)";
            case "presession.right": return "Measure R arm";
            case "presession.left": return "Measure L arm";
            case "presession.sequential": return "Both arms in sequence (right then left)";
            case "presession.err.armXor": return "For shoulder flexion pick right or left (not both)";
            case "presession.sideGuide": return "Stand sideways. Right arm → show right shoulder to camera; left arm → left shoulder.";
            case "presession.frontGuide": return "Face the camera. Raise one or both arms out to the side (abduction) — keep shoulders and head in frame.";
            case "presession.exercise.hint": return "Flexion: side profile, one arm or sequential. Abduction: front view, both arms at once.";
            case "presession.personal": return "Fill fields with suggested targets";
            case "presession.confirm": return "Confirm Targets and Start";
            case "presession.confirm.profile": return "Save Patient";
            case "presession.cancel": return "Cancel";
            case "presession.err.consent": return "Please accept the privacy notice to continue";
            case "presession.err.name": return "First and last name are required";
            case "presession.err.height": return "Enter a valid height (e.g. 170)";
            case "presession.err.age": return "Age must be 1–120 or left blank";
            case "presession.err.gender": return "Select gender (for avatar)";
            case "presession.err.session": return "Height must be 100–250 cm and at least one arm selected";
            case "presession.err.angle": return "Target angle must be between 90–170°";
            case "presession.err.reps": return "Target reps must be between 1–30";
            case "presession.ph.first": return "First name";
            case "presession.ph.last": return "Last name";
            case "presession.target.angle": return "Target angle";
            case "presession.target.reps": return "Target reps";
            case "presession.target.deg": return "{0}°";
            case "presession.target.repn": return "{0}";
            case "presession.err.movement": return "Select a live movement: shoulder flexion or abduction";
            case "presession.exercise": return "Exercise (region → movement)";

            case "exercise.region.shoulder": return "Shoulder";
            case "exercise.region.arm": return "Arm";
            case "exercise.region.elbow": return "Elbow";
            case "exercise.region.neck": return "Neck";
            case "exercise.region.leg": return "Leg";
            case "exercise.region.ankle": return "Ankle";
            case "exercise.move.shoulder.flexion": return "Shoulder flexion";
            case "exercise.move.shoulder.abduction": return "Shoulder abduction";
            case "exercise.move.shoulder.er": return "Shoulder external rotation";
            case "exercise.move.shoulder.ir": return "Shoulder internal rotation";
            case "exercise.move.arm.elevation": return "Arm elevation";
            case "exercise.move.arm.hadduction": return "Horizontal adduction";
            case "exercise.move.elbow.flexion": return "Elbow flexion";
            case "exercise.move.elbow.extension": return "Elbow extension";
            case "exercise.move.neck.flexion": return "Neck flexion";
            case "exercise.move.neck.rotation": return "Neck rotation";
            case "exercise.move.neck.lateral": return "Neck lateral flexion";
            case "exercise.move.leg.hipFlexion": return "Hip flexion";
            case "exercise.move.leg.hipAbduction": return "Hip abduction";
            case "exercise.move.ankle.dorsi": return "Ankle dorsiflexion";
            case "exercise.move.ankle.plantar": return "Ankle plantarflexion";
            case "exercise.notLiveYet": return "Coming soon";
            case "exercise.comingSoon": return " (soon)";

            case "hud.session.active": return "● SESSION ACTIVE";
            case "hud.session.done": return "Session completed";
            case "hud.session.idle": return "Watch the example — start when ready";
            case "hud.session.positioning": return "Set your position first";
            case "hud.example.hint": return "Example movement";
            case "hud.btn.start": return "Start Session";
            case "hud.btn.end": return "End Session";
            case "hud.btn.back": return "Back to Menu";
            case "visit.plan.title": return "Today's movements";
            case "visit.plan.current": return "Up next";
            case "visit.plan.done": return "Done";
            case "visit.complete.title": return "Movement complete";
            case "visit.complete.body": return "{0} finished ({1}/{2})";
            case "visit.complete.next": return "Next: {0}";
            case "visit.complete.continue": return "Continue";
            case "presession.queue.hint": return "Tap a live movement to add or remove it from the sequence.";
            case "hud.strain": return "Strain %{0}";
            case "hud.strain.est": return "Estimate %{0}";
            case "hud.strain.noface": return "Face not found";
            case "hud.frame.hint": return "Keep torso, shoulder and elbow in frame (missing regions are not estimated)";
            case "hud.quality.reliable": return "Quality: reliable";
            case "hud.quality.caution": return "Quality: caution (light/clothing/distance)";
            case "hud.quality.invalid": return "Quality: low — peak ROM unreliable";
            case "hud.assist": return "Help active";
            case "hud.assist.on": return "HELP ON";
            case "hud.assist.auto": return "Contact+vel → assist";
            case "hud.assist.secondPerson": return "2nd person on stage";
            case "hud.rep.right": return "R:";
            case "hud.rep.left": return "L:";
            case "hud.rom.arm.right": return "RIGHT ARM";
            case "hud.rom.arm.left": return "LEFT ARM";
            case "hud.rom.detail": return "Target {0}°  ·  Remaining {1}°  ·  {2}%";
            case "hud.upright": return "Upright lean: {0}°";
            case "hud.upright.yaw": return "Turn: {0}°";
            case "hud.posture.upright.good": return "Sitting upright — good ({0}°)";
            case "hud.posture.upright.warn": return "Sit a bit more upright ({0}°)";
            case "hud.posture.upright.bad": return "Keep your trunk upright ({0}° — over limit)";
            case "hud.posture.facing.good": return "Facing camera — good (turn {0}°)";
            case "hud.posture.facing.warn": return "Turn a little more toward the camera ({0}°)";
            case "hud.posture.facing.bad": return "Face the camera fully (turn {0}°)";
            case "hud.posture.facing.missing": return "Keep torso and face fully visible to the camera";
            case "hud.posture.sideOk": return "Side camera: profile protocol";
            case "pos.step.title": return "Step 1 / 2 — Set your position";
            case "pos.hint.faceCamera": return "Stand sideways — keep shoulders and head in frame";
            case "pos.hint.center": return "Move into the middle zone and hold still";
            case "pos.hint.moveLeft": return "← Move a little to your left";
            case "pos.hint.moveRight": return "Move a little to your right →";
            case "pos.hint.holdGreen": return "Perfect! Hold still in this spot";
            case "pos.hint.head": return "Keep your head visible in frame";
            case "pos.hint.sideMore": return "Turn more sideways (shoulders should look narrow)";
            case "pos.hint.sideWrong": return "Turn so your working shoulder faces the camera";
            case "pos.hint.sideOk": return "Side profile looks good — hold still";
            case "warn.sideSkew": return "Turn more sideways — side profile needed for measurement";
            case "warn.sideInvalid": return "Side profile lost — frame not counted";
            case "warn.headFrame": return "Keep your head in the camera frame";
            case "warn.wrongSide": return "Wrong side: face your working shoulder to the camera";
            case "hud.phase": return "Phase {0}/2 — {1}";
            case "hud.phase.right": return "Right arm";
            case "hud.phase.left": return "Left arm";
            case "report.protocol.side": return "Side profile (shoulder flexion)";
            case "report.protocol.front": return "Front profile (shoulder abduction)";
            case "report.protocol.sequential": return "Both arms sequential";
            case "pos.countdown.subtitle": return "Watch the demo — start the session when ready";
            case "pos.skip.btn": return "Skip position (test)";
            case "hud.pos.skip.on": return "Turn position off";
            case "hud.pos.skip.off": return "Turn position on";

            case "warn.stand": return "Keep your trunk upright";
            case "warn.faceFront": return "Stand in front of the camera — keep your shoulders visible";
            case "warn.turnFront": return "Stand in front of the camera — keep your shoulders visible";
            case "warn.depthCollapse": return "Do not point your straight arm at the camera — lift sideways-up so we can see it";
            case "warn.strain": return "HIGH STRAIN";
            case "warn.repInvalid": return "REP NOT COUNTED - Stand tall!";
            case "warn.trackingJump": return "FRAME / TRACKING JUMP — Steady the camera";
            case "warn.secondPerson": return "2ND PERSON ON STAGE — Assist measurement may apply";
            case "warn.assistNear": return "ASSISTED MEASUREMENT — Hand contact + co-directed velocity";
            case "coach.sessionStart": return "Session starting. Raise sideways-up with control; do not point a straight arm at the camera.";
            case "coach.stand": return "When lifting your arm, do not lean sideways; keep your back upright.";
            case "coach.faceFront": return "Stand in front of the camera; keep your shoulders visible.";
            case "coach.turnFront": return "Stand in front of the camera; keep your shoulders visible.";
            case "coach.depthCollapse": return "Do not point your straight arm at the camera. Lift sideways and up.";
            case "coach.strain": return "Strain is high. Slow down and breathe.";
            case "coach.repInvalid": return "Rep not counted. Stand tall and try again.";
            case "coach.slow": return "Raise more slowly. Stay in control.";
            case "coach.pace": return "Good pace. Keep going.";
            case "coach.almost": return "Almost there. Focus on the last reps.";
            case "coach.targets": return "Today's target is {0} degrees, {1} reps. Keep good posture and raise with control.";
            case "target.default": return "Default targets";
            case "target.hard": return "Suggestion: {0}° / {1} reps (previous session was hard)";
            case "target.ok": return "Suggestion: {0}° / {1} reps (previous ROM {2}°)";

            case "report.title": return "Physiotherapy Session Report";
            case "report.session": return "Session";
            case "report.rightMax": return "R Max ROM";
            case "report.leftMax": return "L Max ROM";
            case "report.rightAvg": return "R Avg ROM";
            case "report.leftAvg": return "L Avg ROM";
            case "report.rightReps": return "R Reps";
            case "report.leftReps": return "L Reps";
            case "report.targetAngle": return "Target Angle";
            case "report.compensation": return "Compensation";
            case "report.duration": return "Duration";
            case "report.peakStrain": return "Peak Strain";
            case "report.meanStrain": return "Mean Strain";
            case "report.quality.mean": return "Quality score (mean)";
            case "report.quality.band": return "Quality band";
            case "report.quality.reliable": return "Reliable";
            case "report.quality.caution": return "Caution";
            case "report.quality.invalid": return "Low / invalid";
            case "report.quality.unknown": return "Unknown";
            case "report.series.right": return "R arm";
            case "report.series.left": return "L arm";
            case "report.patient": return "Patient";
            case "report.invalid": return "invalid";
            case "report.arms.both": return "R + L";
            case "report.arms.right": return "R";
            case "report.arms.left": return "L";
            case "report.progress.title": return "Progress Report";
            case "report.progress.chart": return "ROM Progress Across Sessions";
            case "report.progress.history": return "Session History";
            case "report.progress.clickHint": return "Click a table row or a chart point to open the session summary.";
            case "stats.title": return "Progress statistics (PS-1.1)";
            case "stats.sessions": return "Session count";
            case "report.assisted.right": return "Assisted reps (R)";
            case "report.assisted.left": return "Assisted reps (L)";
            case "report.assisted.total": return "Assisted reps (total)";
            case "detail.note.assisted": return "• Assisted reps: {0} (independent {1}).";
            case "detail.note.trackingJump": return "• Tracking/frame jump: {0} event(s) — ROM reliability may be reduced.";
            case "detail.note.secondPerson": return "• 2nd person on stage: {0} event(s) (logged even if help toggle was off).";
            case "detail.note.assistNear": return "• Assisted cue (contact + velocity + persistence): {0} event(s).";
            case "report.trackingJump": return "Tracking jumps";
            case "report.secondPerson": return "2nd person on stage";
            case "report.assistNear": return "Assisted cue";
            case "stats.romTrend": return "ROM trend (first→last)";
            case "stats.romTrendRight": return "Right ROM trend";
            case "stats.romTrendLeft": return "Left ROM trend";
            case "stats.completion": return "Mean completion";
            case "stats.invalidRate": return "Invalid rep rate";
            case "stats.assistedRate": return "Assisted rep rate";
            case "stats.repsIndep": return "Independent reps (total)";
            case "stats.repsAssisted": return "Assisted reps (total)";
            case "stats.sessionsWeek": return "Observed sessions/week";
            case "stats.plannedWeek": return "Planned sessions/week";
            case "stats.adherence": return "Adherence";
            case "stats.meanRom": return "Mean max ROM";
            case "stats.qwMeanRom": return "Quality-weighted mean ROM";
            case "stats.meanQuality": return "Mean quality score";
            case "stats.meanPeakStrain": return "Mean peak strain";
            case "stats.compSessions": return "Sessions with compensation";
            case "stats.eventsComp": return "Compensation events";
            case "stats.eventsJump": return "Tracking jumps";
            case "stats.eventsSecond": return "2nd-person events";
            case "stats.eventsAssistNear": return "Assist proximity events";
            case "stats.formula": return "Formula version";
            case "stats.note": return "Summary is computed over all exported sessions; the filter below only affects the table/chart. Decision support; not a diagnosis.";
            case "report.progress.axisHint": return "Vertical axis: angle (°). Horizontal axis: session number (steps 5 / 10 / 15 / 20 / 30 when needed).";
            case "report.progress.xAxis": return "Session #";
            case "report.progress.yAxis": return "Angle (°)";
            case "report.metrics": return "Metrics:";
            case "report.maxRom": return "Max ROM";
            case "report.avgRom": return "Avg ROM";
            case "report.col.date": return "Date";
            case "report.col.validTarget": return "Valid/Target";
            case "report.col.invalid": return "Invalid";
            case "report.col.strain": return "Strain";
            case "report.firstMax": return "First Max ROM";
            case "report.lastMax": return "Last Max ROM";
            case "report.change": return "Change";
            case "report.disclaimer": return "This report is for clinical decision support only and does not replace a diagnosis. Evaluation must be done by a clinician. Personal data stays on this device only.";
            case "report.disclaimer.short": return "This report is for clinical decision support only and does not replace a diagnosis.";
            case "report.notes": return "Clinical Notes";
            case "report.survey.btn": return "Clinician: post-session answers";
            case "report.survey.btn.hide": return "Hide answers";
            case "report.survey.title": return "Post-session self-report";
            case "report.survey.hint": return "Hidden by default. Clinician opens this. Not a diagnosis.";
            case "report.survey.col.q": return "Question";
            case "report.survey.col.a": return "Answer";
            case "report.survey.none": return "No survey recorded for this session.";
            case "face.btn": return "Face Calibration";
            case "face.title": return "Face Strain Calibration";
            case "face.hint": return "First 15 s relaxed face, then 60 s strain expressions (frown, squint, jaw clench).\nRaw video is not recorded.";
            case "face.ready": return "Ready — press Start";
            case "face.start": return "Start Calibration";
            case "face.skip": return "Skip (legacy mode)";
            case "face.cancel": return "Cancel";
            case "face.rest.title": return "1/2 — Relaxed face";
            case "face.rest.hint": return "Look at the camera and relax your face. Do not talk or frown.";
            case "face.rest.progress": return "Rest {0} · samples {1}";
            case "face.strain.title": return "2/2 — Strain expressions (~1 min)";
            case "face.strain.hint": return "Show the faces you make under strain: frown, squint, jaw/lip press, nose wrinkle. Vary and repeat.";
            case "face.strain.progress": return "Strain {0} · samples {1}";
            case "face.noface": return " — face not found";
            case "face.saved": return "Calibration saved.";
            case "report.person": return "Personal Information";
            case "report.name": return "Full name";
            case "report.reasonForCare": return "Reason for physiotherapy";
            case "report.height": return "Height";
            case "report.age": return "Age";
            case "report.gender": return "Gender";
            case "report.arms": return "Measured arm";
            case "report.movement": return "Movement";
            case "report.protocol": return "Protocol";
            case "report.sessionNo": return "Session no";
            case "report.date": return "Date";
            case "report.male": return "Male";
            case "report.female": return "Female";
            case "common.yes": return "Yes";
            case "common.no": return "No";

            case "menu.btn.program": return "My Program";
            case "menu.btn.notes": return "Patient Notes";
            case "menu.btn.clinician": return "Clinician Login";
            case "notes.title": return "Patient Notebook";
            case "notes.patient": return "Patient: {0}";
            case "notes.noPatient": return "No active patient selected";
            case "notes.path": return "File: {0}";
            case "notes.placeholder": return "Clinical observations, home exercise notes, alerts…";
            case "notes.btn.save": return "Save";
            case "notes.btn.reload": return "Reload";
            case "notes.btn.openFile": return "Open File";
            case "notes.btn.close": return "Save & Exit";
            case "notes.saved": return "Notes saved.";
            case "notes.saveFailed": return "Save failed.";
            case "notes.reloaded": return "Reloaded from file.";
            case "notes.openedExternal": return "Opened in Notepad / default app.";
            case "notes.openFailed": return "Could not open file.";
            case "picker.title": return "Select patient";
            case "picker.hint": return "Search or pick a recent patient. Confirm to avoid the wrong profile.";
            case "picker.searchPh": return "Search first or last name…";
            case "picker.recent": return "Recently used";
            case "picker.all": return "All patients";
            case "picker.results": return "Search results";
            case "picker.empty": return "No registered patients. Add a new patient.";
            case "picker.new": return "+ New patient";
            case "picker.confirmTitle": return "Confirm patient";
            case "picker.confirmBody": return "This session: {0}?";
            case "picker.confirmContinue": return "Continue";
            case "picker.confirmBack": return "Back";
            case "picker.active": return "Active patient: {0}";
            case "picker.activeNone": return "No active patient selected";
            case "picker.yearsSuffix": return " yrs";
            case "picker.sessions": return "{0} sessions";
            case "picker.change": return "Change patient";
            case "picker.edit": return "Edit details";

            case "presession.title.edit": return "Edit patient details";
            case "presession.confirm.edit": return "Save changes";

            case "assess.banner": return "Assessment session {0}/{1}";
            case "assess.live.start": return "ROM analysis: lift your arm as far as you can";
            case "assess.live.measuring": return "Analyzing…";
            case "assess.live.ready": return "Target {0}° · slider full ≈ {1}° — start reps!";
            case "survey.title.assess": return "Assessment survey ({0}/{1})";
            case "survey.title.checkin": return "Post-session check-in";
            case "survey.hint": return "0 bad, 5 neutral, 10 good. Tap “Don’t know” if unsure. Not a diagnosis.";
            case "survey.progress": return "Question {0}/{1}";
            case "survey.next": return "Next";
            case "survey.unknown": return "Don’t know";
            case "survey.q.difficulty": return "How easy was this session? (0 very hard – 10 very easy)";
            case "survey.q.pain": return "How comfortable were you during the session? (0 severe pain – 10 no pain)";
            case "survey.q.motivation": return "Motivation? (0 low – 10 high)";
            case "survey.q.fatigue": return "How fresh do you feel? (0 exhausted – 10 very fresh)";
            case "survey.q.homeDays": return "Home exercise days in last 7 days? (0 none – 7 every day)";
            case "survey.q.sleep": return "Sleep quality? (0 poor – 10 good)";
            case "survey.q.confidence": return "Confidence you moved correctly? (0 low – 10 high)";
            case "survey.q.willingness": return "Willingness to continue tomorrow? (0 none – 10 very willing)";
            case "careplan.title": return "My training program";
            case "careplan.empty": return "No program yet. Complete assessment sessions.";
            case "careplan.forPatient": return "Patient: {0}";
            case "careplan.phase.assess": return "Assessment phase";
            case "careplan.phase.active": return "Active program";
            case "careplan.assess.progress": return "Assessment in progress: {0} / {1} sessions done.\n\nThe program is created after session 5.";
            case "careplan.summary.default": return "Starter program (cautious).";
            case "careplan.summary.cautious": return "Cautious plan: {0}° / {1} reps, {2} sessions/week.";
            case "careplan.summary.progress": return "Progress plan: {0}° / {1} reps, {2} sessions/week.";
            case "careplan.summary.deload": return "Load reduced (deload): {0}° / {1} reps.";
            case "careplan.section.todayTarget": return "Today's target";
            case "careplan.section.week": return "This week";
            case "careplan.section.month": return "Monthly plan";
            case "careplan.metric.angle": return "Target angle";
            case "careplan.metric.reps": return "Reps";
            case "careplan.metric.sessionsWeek": return "Sessions / week";
            case "careplan.metric.intensity": return "Intensity";
            case "careplan.daily": return "Daily target: {0}° · {1} reps";
            case "careplan.weekly": return "Weekly: {0} sessions · intensity: {1}";
            case "careplan.today.train": return "Training day today";
            case "careplan.today.rest": return "Rest / light day today";
            case "careplan.monthly.title": return "Monthly outline:";
            case "careplan.monthly.week": return "  Week {0}: {1}° / {2} reps ({3})";
            case "careplan.monthly.weekClean": return "Week {0}   ·   {1}°   ·   {2} reps   ·   {3}";
            case "careplan.intensity.easy": return "easy";
            case "careplan.intensity.standard": return "standard";
            case "careplan.intensity.deload": return "deload";
            case "careplan.presession.fromPlan": return "From program: {0}° / {1} reps";
            case "clinician.title": return "Clinician access";
            case "clinician.enterPin": return "Enter PIN (clinician only)";
            case "clinician.setPin": return "First setup: choose a 4–8 digit PIN";
            case "clinician.unlock": return "Unlock / Report";
            case "clinician.unlockHtml": return "Open with PIN";
            case "clinician.pinForReport": return "Enter PIN to access encrypted reports";
            case "clinician.inapp.patient": return "Patient: {0}";
            case "clinician.inapp.reason": return "Why PT: {0}";
            case "clinician.inapp.noPatient": return "No active patient selected";
            case "clinician.inapp.phase.assess": return "Assessment phase — {0}/{1} sessions";
            case "clinician.inapp.phase.active": return "Active program (version {0})";
            case "clinician.inapp.plan": return "Target {0}° / {1} reps · {2} sessions/week · last adapted: {3}";
            case "clinician.inapp.sessions": return "Recorded sessions: {0}";
            case "clinician.inapp.note.header": return "Session #{0} · {1} · {2}";
            case "clinician.inapp.note.claim": return "Patient claim: {0}";
            case "clinician.inapp.note.obs": return "Observed: {0}";
            case "clinician.err.format": return "PIN must be 4–8 digits";
            case "clinician.err.pin": return "Incorrect PIN";
            case "clinician.showPin": return "Show password";
            case "clinician.hidePin": return "Hide password";
            case "clinician.report.title": return "Clinician decision-support report";
            case "clinician.report.phase": return "Phase";
            case "clinician.report.plan": return "Current plan";
            case "clinician.report.sessions": return "Session summary";
            case "clinician.report.notes": return "Discrepancy notes (patient cannot see)";
            case "clinician.report.noNotes": return "No discrepancy notes recorded.";
            case "clinician.report.disclaimer": return "Decision-support only; not a diagnosis or treatment plan. Notes are clinician-access only.";
            case "clinician.claim.easy": return "Session felt easy ({0}/10)";
            case "clinician.claim.hard": return "Session felt hard ({0}/10)";
            case "clinician.claim.noPain": return "No pain reported ({0}/10 comfort)";
            case "clinician.claim.dailyHome": return "Home exercise claimed {0} days/week";
            case "clinician.obs.strain": return "Peak strain %{0}, compensation {1}, invalid {2}";
            case "clinician.obs.comp": return "Compensation {0}, invalid reps {1}";
            case "clinician.obs.lowLoad": return "Completion %{0}, low strain %{1}, no compensation";
            case "clinician.obs.frequency": return "App session frequency ~{0}/week";
            case "vault.enterPin": return "Patient report folder is locked — enter clinician PIN";
            case "vault.unlock": return "Unlock";
            case "vault.openFailed": return "Could not open report. Unlock with PIN.";
            case "vault.lockedHint": return "Each patient has a separate encrypted folder. Doctor PIN required to open.";
            case "vault.migrated": return "{0} legacy report(s) moved into patient folder(s).";

            default: return key;
        }
    }
}
